version: "3.9"

services:
  api_express:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app:rw
    depends_on:
      todo_db:
        condition: service_healthy

  todo_db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 30s
